---
#    msg: "Variable delete_previous_k8s_install is set to {{ delete_previous_k8s_install }} ! Supported values are : True, False"
#  when: (delete_previous_k8s_install | string) not in ['True','False']

- name: check rotate certificates
  fail:
    msg: "Rotate certificates {{ agorakube_pki.management.rotate_certificats }} is not supported ! Supported values are : true, false"
  when: (agorakube_pki.management.rotate_certificats| string| lower) not in ['true', 'false']

- name: check Upgrade Kubernetes release
  fail:
    msg: "Kubernetes release {{ agorakube_base_components.kubernetes.upgrade }} is not supported ! Supported values are : true, false"
  when: (agorakube_base_components.kubernetes.upgrade| string| lower) not in ['true', 'false']

- name: check enable external loadbalancing
  fail:
    msg: "External_loadbalancing {{ agorakube_network.external_loadbalancing.enabled }} is not supported ! Supported values are : true, false"
  when: (agorakube_network.external_loadbalancing.enabled| string| lower) not in ['true', 'false']

- name: check Enable Kubernetes dashboard
  fail:
    msg: "Variable agorakube_features.dashboard.enabled is set to : {{ agorakube_features.dashboard.enabled }} . Not supported ! Supported values are : true, false"
  when: (agorakube_features.dashboard.enabled| string| lower) not in ['true', 'false']

- name: check enable default admin user for Kubernetes Dashboard
  fail:
    msg: "Variable agorakube_features.dashboard.generate_admin_token is set to : {{ agorakube_features.dashboard.generate_admin_token }} . Not supported ! Supported values are : true, false"
  when: (agorakube_features.dashboard.generate_admin_token| string| lower) not in ['true', 'false']

- name: Check enable Metric-Server
  fail:
    msg: "Variable agorakube_features.metrics_server.enabled is set to : {{ agorakube_features.metrics_server.enabled }} . Not supported ! Supported values are : true, false"
  when: (agorakube_features.metrics_server.enabled| string| lower) not in ['true', 'false']

- name: check ETCD cluster status and Health
  fail:
    msg: "Variable agorakube_base_components.etcd.check is set to : {{ agorakube_base_components.etcd.check }} . Not supported ! Supported values are :  true, false"
  when: (agorakube_base_components.etcd.check| string| lower) not in ['true', 'false']

- name: check Enable ETCD cluster backup
  fail:
    msg: "Variable agorakube_base_components.etcd.backup.enabled is set to : {{ agorakube_base_components.etcd.backup.enabled }} . Not supported ! Supported values are :  true, false"
  when: (agorakube_base_components.etcd.backup.enabled| string| lower) not in ['true', 'false']

- name: Check Populate /etc/hosts
  fail:
    msg: "Variable agorakube_populate_etc_hosts is set to : {{ agorakube_populate_etc_hosts }} ! Supported values are : true, false"
  when: (agorakube_populate_etc_hosts| string| lower) not in ['true', 'false']

- name: Check runtime variable
  fail:
    msg: "Variable agorakube_base_components.container.engine is set to :  {{ agorakube_base_components.container.engine }} is not supported ! Supported values are : docker, containerd, none, false"
  when: (agorakube_base_components.container.engine| string| lower) not in ['containerd','false','none']

- name: Check CNI plugin used
  fail:
    msg: "CNI plugin used {{ agorakube_network.cni_plugin }} is not supported ! Supported values are : calico, kube-router, none"
  when: (agorakube_network.cni_plugin| string| lower) not in ['calico','none']

- name: Check Kube-Proxy mode
  fail:
    msg: "Kube-Proxy mode {{ agorakube_network.kube_proxy.mode }} is not supported ! Supported values are : ipvs, none, false"
  when: (agorakube_network.kube_proxy.mode| string| lower) not in ['ipvs','false','none']

- name: Check Default ClusterIP loadBalancing Algorithm
  fail:
    msg: "Default ClusterIP loadBalancing Algorithm {{ agorakube_network.kube_proxy.algorithm }} is not supported ! Supported values are : rr, lc, dh, sh, sed, nq, none"
  when: (agorakube_network.kube_proxy.algorithm| string| lower) not in ['rr','lc','dh','sh','sed','nq','none']

#- name: Check Jiva FS types
#  fail:
#    msg: "Jiva FS types {{ agorakube_features.storage.jiva.fs_type }} is not supported ! Supported values are : ext4, none, false"
#  when: (agorakube_features.storage.jiva.fs_type| string| lower) not in ['ext4','false','none']

- name: check Ingress Controller
  fail:
    msg: "Ingress Controller {{ agorakube_features.ingress.controller }} is not supported ! Supported values are : none, traefik, haproxy, nginx"
  when: (agorakube_features.ingress.controller| string| lower) not in ['none','nginx']

- name: Check cluster_cidr
  fail:
    msg: "Variable cluster_cidr must be an IP adresse CIDR !"
  when: agorakube_network.cidr.service is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check service_cluster_ip_range
  fail:
    msg: "Variable service_cluster_ip_range must be an IP adresse CIDR !"
  when: agorakube_network.external_loadbalancing.ip_range is not regex("(?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])")

- name: Check kubernetes_service
  fail:
    msg: "agorakube_network.service_ip.kubernetes must be an IP adresse from service_cluster_ip_range !"
  when: agorakube_network.service_ip.kubernetes is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check cluster_dns_ip
  fail:
    msg: "agorakube_network.service_ip.corednsmust be an IP adresse from service_cluster_ip_range "
  when: agorakube_network.service_ip.coredns is not regex("^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$")

- name: Check Node Port Range
  fail:
    msg: "Variable must be INT-INT => sample : 30000-32767"
  when: agorakube_network.nodeport.range is not regex("(?:[+-]?(?:[0-9]+))-(?:[+-]?(?:[0-9]+))")

- name: Check data_path variable
  fail:
    msg: "Variable data_path must be a valid linux path ! Get {{ agorakube.global.data_path }}"
  when: agorakube.global.data_path is not regex("^(\/[^\/ ]*)+\/?$")

- name : check kubernetes release
  fail:
    msg: "Variable agorakube_base_components.kubernetes.release is set to : {{ agorakube_base_components.kubernetes.release }} . Not supported ! Supported values have the following patern : vX.X.X - Sample: v1.22.0"
  when: agorakube_base_components.kubernetes.release is not regex ("^v(?:[+-]?(?:[0-9]+)).(?:[+-]?(?:[0-9]+)).(?:[+-]?(?:[0-9]+))?$")

- name : check ETCD release
  fail:
    msg: "Variable agorakube_base_components.etcd.release is set to : {{ agorakube_base_components.etcd.release }} . Not supported ! Supported values have the following pattern : vX.X.X - Sample: v3.4.14"
  when: agorakube_base_components.etcd.release is not regex ("^v(?:[+-]?(?:[0-9]+)).(?:[+-]?(?:[0-9]+)).(?:[+-]?(?:[0-9]+))?$")

- name: Check agorakube_base_components.etcd.data_path variable
  fail:
    msg: "Variable agorakube_base_components.etcd.data_path must be a valid linux path ! Get {{ agorakube_base_components.etcd.data_path }}"
  when: agorakube_base_components.etcd.data_path is not regex("^(\/[^\/ ]*)+\/?$")