
---
- name: Creatopn dossiers /etc/kubernetes/pki /etc/kubernetes/pki/etcd
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/pki
    - /etc/kubernetes/pki/etcd

- name: Import certificates etcd/ca.crt
  copy:
    src: "{{ data_path }}/certificates/intermediate/etcd-ca/signed/etcd-ca.pem"
    dest: /etc/kubernetes/pki/etcd/ca.crt
  notify:
    - Restart etcd

- name: Import etcd/server.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-etcd/kube-etcd-key.pem"
    dest: /etc/kubernetes/pki/etcd/server.key
  notify:
    - Restart etcd

- name: Import etcd/server.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-etcd/kube-etcd.pem"
    dest: /etc/kubernetes/pki/etcd/server.crt
  notify:
    - Restart etcd

- name: Import etcd/peer.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-etcd-peer/{{ ansible_fqdn }}/kube-etcd-peer-key.pem"
    dest: /etc/kubernetes/pki/etcd/peer.key
  notify:
    - Restart etcd

- name: Import etcd/peer.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-etcd-peer/{{ ansible_fqdn }}/kube-etcd-peer.pem"
    dest: /etc/kubernetes/pki/etcd/peer.crt
  notify:
    - Restart etcd

- name: Import etcd/healthcheck-client.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-etcd-healthcheck-client/kube-etcd-healthcheck-client-key.pem"
    dest: /etc/kubernetes/pki/etcd/healthcheck-client.key
  notify:
    - Restart etcd

- name: Import etcd/healthcheck-client.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-etcd-healthcheck-client/kube-etcd-healthcheck-client.pem"
    dest: /etc/kubernetes/pki/etcd/healthcheck-client.crt
  notify:
    - Restart etcd
