---
- name: stop docker
  systemd:
    state: stopped
    name: docker
  tags: [ 'never', 'uninstall' ]
  ignore_errors: yes

- name: Uninstall docker
  package:
    name: ["docker-ce","docker-ce-cli"]
    state: absent
  when: agorakube_base_components.container.release|length == 0
  tags: ['never', 'uninstall']

- name: Uninstall docker in specific release
  package:
    name: ["docker-ce={{ agorakube_base_components.container.release }}","docker-ce-cli={{ agorakube_base_components.container.release }}"]
    state: absent
  when: agorakube_base_components.container.release|length > 0
  tags: ['never', 'uninstall']

- name: uninstall Docker for Debian lagorakube distros
  file:
    path: "docker-debian-like.yaml"
    state: absent
  when: is_debian_like
  tags: ['never', 'uninstall']

- name: uninstall Docker for Centos lagorakube distros
  file:
    path: "docker-centos-like.yaml"
    state: absent
  when: is_centos_like
  tags: ['never', 'uninstall']

- name : Delete Docker config files
  file:
    path: "/etc/docker"
    state: absent
  tags: ['never', 'uninstall']

- name: Delete all Docker  Network interfaces presents on the host
  file:
    path: "/var/lib/cni/networks"
    state: absent
  tags: ['never', 'uninstall']

- name: Delete plugin CNI
  file:
    path: /etc/cni/net.d
    state: absent
  tags: ['never', 'uninstall']

- name: Delete /var/lib/docker
  file:
    path: /var/lib/docker
    state: absent
  tags: ['never', 'uninstall']

- name: Delete /var/lib/dockershim
  file:
    path: /var/lib/dockershim
    state: absent
  tags: ['never', 'uninstall']

- name: Delete /var/run/dockershim.sock
  file:
    path: /var/run/dockershim.sock
    state: absent
  tags: ['never', 'uninstall']

- name: Delete /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    state: absent
  tags: ['never', 'uninstall']

- name: Unmount /var/run/docker/netns/default volumes
  mount:
    path: /var/run/docker/netns/default
    state: unmounted
  tags: ['never', 'uninstall']

- name: Delete /var/run/docker dir
  file:
    path: /var/run/docker
    state: absent
  tags: ['never', 'uninstall']
