---
- name: Create master dir hierarchy
  file:
    path: /etc/kubernetes/manifests
    state: directory
    owner: root
    group: root
    mode: '644'
    recurse: True

- name: Download Kubernetes server binaries
  unarchive:
    src: https://dl.k8s.io/{{ kubernetes_release }}/kubernetes-server-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/kubernetes/server/bin/kube-apiserver

#- name: Retrive all keys to authenticate K8S service account tokens
#  find:
#    paths: "{{ pki_path }}/sa"
#  register: token_keys

- name: Import kubernetes master services definitions in /etc/systemd/system/
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '644'
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  notify:
    - Restart kube-apiserver service
    - Restart kube-controller-manager service
    - Restart kube-scheduler service


- name: Import kube-apiserver configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/manifests/{{ item }}
    owner: root
    group: root
    mode: '644'
  with_items:
    - eventconfig.yaml
    - admission-control-config-file.yaml
    - audit-policy.yaml
  notify:
    - Restart kube-apiserver service

- name: Import controller-manager.conf kubeconfig
  copy:
    src: "{{ pki_path }}/kubeconfigs/controller-manager/controller-manager.conf"
    dest: /etc/kubernetes/manifests/controller-manager.conf
    owner: root
    group: root
    mode: '644'
  notify:
    - Restart kube-controller-manager service

- name: Import kube scheduler yaml file config
  template:
    src: kube-scheduler.yaml.j2
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    owner: root
    group: root
    mode: '644'
  notify:
    - Restart kube-scheduler service

- name: Import /etc/kubernetes/manifests/scheduler.conf
  copy:
    src: "{{ pki_path }}/kubeconfigs/scheduler/scheduler.conf"
    dest: /etc/kubernetes/manifests/scheduler.conf
    owner: root
    group: root
    mode: '644'
  notify:
    - Restart kube-scheduler service

- name: Inject kube-encrypt config
  template:
    src: encryption-provider-config.yaml.j2
    dest: /etc/kubernetes/manifests/encryption-provider-config.yaml
    owner: root
    group: root
    mode: '644'
  notify:
    - Restart kube-apiserver service

- name: Load [kube-apiserver] [kube-controller-manager] [kube-scheduler]
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
